services:
  - type: web
    name: portfolio-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: UseSqlite
        value: false
      - key: ConnectionStrings__Postgres
        value: SET_IN_RENDER_DASHBOARD
    healthCheckPath: /api/health
    autoDeploy: true
